---
- name: Install additional tools
  become: true
  ansible.builtin.yum:
    name:
      - "libstdc++"
      - "glibc"
    state: present
- name: Install Vector packages
  become: true
  ansible.builtin.yum:
    name: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
    state: present