---
- name: Downloading Vector package
  include_tasks: download/{{ ansible_pkg_mgr }}.yml

- name: Install Vector packages
  include_tasks: install/{{ ansible_pkg_mgr }}.yml
  
- name: copy Vector config
  become: true
  ansible.builtin.template:
    mode: 0644
    src: templates/vector.yaml.j2
    dest: "{{ vector_config_dest }}"
    # owner: "{{ ansible_user_id }}"
    # group: "{{ ansible_user_gid }}"
    backup: true
    validate: vector validate --no-environment --config-yaml %s
- name: Start vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
