---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos 8
    image: centos:8
    pre_build_image: true
  - name: ubuntu
    image: ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
