---
- name: Downloading Vector package
  ansible.builtin.get_url:
    mode: 0644
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector_{{ vector_version }}-1_amd64.deb"